# session-sync-init.ps1 - Initialize ~/.claude/projects as a git repo for session sync
# Usage: Called by install.ps1, or manually: .\session-sync-init.ps1
# Syncs session JSONL in projects/ to private repo nirecom/claude-sessions

param(
    [string]$ClaudeDir = (Join-Path $env:USERPROFILE ".claude"),
    [string]$RemoteUrl = "https://github.com/nirecom/claude-sessions.git",
    [switch]$NoRemote
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Warning "Git is required for session sync."
    return
}

$ProjectsDir = Join-Path $ClaudeDir "projects"
if (-not (Test-Path $ProjectsDir)) {
    New-Item -ItemType Directory -Path $ProjectsDir -Force | Out-Null
}

# Migrate old git root from ~/.claude/ to ~/.claude/projects/
if (Test-Path (Join-Path $ClaudeDir ".git")) {
    Write-Host "Migrating git root from $ClaudeDir to $ProjectsDir..."
    Remove-Item (Join-Path $ClaudeDir ".git") -Recurse -Force
    Remove-Item (Join-Path $ClaudeDir ".gitignore") -Force -ErrorAction SilentlyContinue
    Remove-Item (Join-Path $ClaudeDir ".gitattributes") -Force -ErrorAction SilentlyContinue
}

# Initialize git repo if not already
if (-not (Test-Path (Join-Path $ProjectsDir ".git"))) {
    Write-Host "Initializing git repo in $ProjectsDir..."
    git init $ProjectsDir
} else {
    Write-Host "Git repo already exists in $ProjectsDir." -ForegroundColor DarkGray
}

# Create .gitattributes (overwrite for idempotency)
$gitattributesContent = @"
# All files under this repo are machine-generated by Claude Code
* text eol=lf
"@

[System.IO.File]::WriteAllText((Join-Path $ProjectsDir ".gitattributes"), ($gitattributesContent -replace "`r`n", "`n") + "`n")

# Set remote
if (-not $NoRemote) {
    $existingRemotes = git -C $ProjectsDir remote 2>$null
    if ($existingRemotes -contains "origin") {
        git -C $ProjectsDir remote set-url origin $RemoteUrl
    } else {
        git -C $ProjectsDir remote add origin $RemoteUrl
    }
    Write-Host "Remote set to $RemoteUrl"
}

# Initial commit if no commits yet
$hasCommits = $false
try { $hasCommits = [int](git -C $ProjectsDir rev-list --count HEAD 2>$null) -gt 0 } catch {}
if (-not $hasCommits) {
    git -C $ProjectsDir add .gitattributes
    git -C $ProjectsDir add .
    git -C $ProjectsDir commit -m "Initial session sync from $env:COMPUTERNAME"
    if (-not $NoRemote) {
        git -C $ProjectsDir push -u origin main
    }
}

Write-Host "Session sync initialized." -ForegroundColor Green
