format = """$username$hostname$directory$python$git_branch$git_status$character"""

[username]
show_always = true
style_user = "green bold"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "green bold"
format = "[@$hostname]($style)"

[directory]
style = "cyan"
format = "[:$path]($style) "
truncation_length = 8

[git_branch]
style = "red"
format = "[($branch)]($style)"

[git_status]
style = "red"
format = "[$all_status$ahead_behind]($style)"

[python]
format = '[(\($virtualenv\))]($style) '
style = "yellow"
detect_extensions = []
detect_files = []
detect_folders = []

[character]
success_symbol = "[>](white)"
error_symbol = "[>](red)"
