#!/bin/bash
# Always resolve DOTFILES_DIR from this script's location so that ~/.dotfiles_env
# reflects where the repo actually lives, not whatever was inherited from the parent shell.
DOTFILES_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
export DOTFILES_DIR

# Generate ~/.dotfiles_env so shell rc files (.bash_profile, .zshrc) can locate the repo
# regardless of where it has been cloned.
cat > "$HOME/.dotfiles_env" <<EOF
# Generated by install/linux/dotfileslink.sh — do not edit by hand.
export DOTFILES_DIR="$DOTFILES_DIR"
EOF

#ln -sf "$DOTFILES_DIR/.bashrc" ~/ # Ubuntu has .bashrc by default
ln -sf "$DOTFILES_DIR/.bash_profile" ~/
#ln -sf "$DOTFILES_DIR/.bash_logout" ~/
ln -sf "$DOTFILES_DIR/.zshrc" ~/
ln -sf "$DOTFILES_DIR/.vimrc" ~/
#ln -sf "$DOTFILES_DIR/.vim" ~/
ln -sf "$DOTFILES_DIR/.editorconfig" ~/
ln -sf "$DOTFILES_DIR/.tmux.conf" ~/
ln -sf "$DOTFILES_DIR/.inputrc" ~/

# Private context directory (gitignored)
mkdir -p "$DOTFILES_DIR/.context-private"

# Git config
mkdir -p ~/.config
if [ ! -e ~/.config/git ]; then
    ln -sf "$DOTFILES_DIR/.config/git" ~/.config/
fi

# Generate OS-specific git config.local
GIT_CONFIG_LOCAL="$DOTFILES_DIR/.config/git/config.local"
if [ ! -e "$GIT_CONFIG_LOCAL" ]; then
    source "$DOTFILES_DIR/bin/detectos.sh"
    case "$OSDIST" in
        macos)
            cat > "$GIT_CONFIG_LOCAL" << 'EOF'
[credential]
    helper = osxkeychain
EOF
            ;;
    esac
fi


# Starship config
if [ ! -e ~/.config/starship.toml ]; then
    ln -sf "$DOTFILES_DIR/.config/starship.toml" ~/.config/
fi

# Emacs
mkdir -p ~/.emacs.d
ln -sf "$DOTFILES_DIR/.emacs.d/init.el" ~/.emacs.d/
ln -sf "$DOTFILES_DIR/.emacs.d/inits" ~/.emacs.d/
#ln -sf "$DOTFILES_DIR/.emacs.d/package-install.el" ~/.emacs.d/
#ln -sf "$DOTFILES_DIR/.emacs.d/packages" ~/.emacs.d/
mkdir -p ~/tmp
mkdir -p ~/.emacs_backup


if [ -e ~/.ssh/ssh-add-all ]; then
    chmod +x ~/.ssh/ssh-add-all
fi
