#!/bin/bash
# Always resolve DOTFILES_DIR from this script's location so that ~/.dotfiles_env
# reflects where the repo actually lives, not whatever was inherited from the parent shell.
DOTFILES_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
export DOTFILES_DIR

source "$DOTFILES_DIR/bin/colors.sh"

link_file() {
    local source="$1" dest="$2"
    if [ -L "$dest" ]; then
        local current_target
        current_target="$(readlink "$dest")"
        if [ "$current_target" = "$source" ]; then
            printf "${C_GRAY}Already linked: $dest${C_RESET}\n"
            return
        fi
        printf "${C_YELLOW}Relinking: $dest${C_RESET}\n"
        printf "${C_GRAY}  was: $current_target${C_RESET}\n"
        printf "${C_GRAY}  now: $source${C_RESET}\n"
    elif [ -e "$dest" ]; then
        local backup="$dest.bak"
        printf "${C_YELLOW}Backing up: $dest -> $backup${C_RESET}\n"
        mv "$dest" "$backup"
    fi
    ln -sf "$source" "$dest"
    printf "${C_GREEN}Linked: $dest -> $source${C_RESET}\n"
}

# Generate ~/.dotfiles_env so shell rc files (.bash_profile, .zshrc) can locate the repo
# regardless of where it has been cloned.
cat > "$HOME/.dotfiles_env" <<EOF
# Generated by install/linux/dotfileslink.sh — do not edit by hand.
export DOTFILES_DIR="$DOTFILES_DIR"
EOF

#link_file "$DOTFILES_DIR/.bashrc" ~/ # Ubuntu has .bashrc by default
link_file "$DOTFILES_DIR/.bash_profile" "$HOME/.bash_profile"
#link_file "$DOTFILES_DIR/.bash_logout" "$HOME/.bash_logout"
link_file "$DOTFILES_DIR/.zshrc" "$HOME/.zshrc"
link_file "$DOTFILES_DIR/.vimrc" "$HOME/.vimrc"
#link_file "$DOTFILES_DIR/.vim" "$HOME/.vim"
link_file "$DOTFILES_DIR/.editorconfig" "$HOME/.editorconfig"
link_file "$DOTFILES_DIR/.tmux.conf" "$HOME/.tmux.conf"
link_file "$DOTFILES_DIR/.inputrc" "$HOME/.inputrc"

# Private context directory (gitignored)
mkdir -p "$DOTFILES_DIR/.context-private"

# Git config
mkdir -p ~/.config
link_file "$DOTFILES_DIR/.config/git" "$HOME/.config/git"

# Generate OS-specific git config.local
GIT_CONFIG_LOCAL="$DOTFILES_DIR/.config/git/config.local"
if [ ! -e "$GIT_CONFIG_LOCAL" ]; then
    source "$DOTFILES_DIR/bin/detectos.sh"
    case "$OSDIST" in
        macos)
            cat > "$GIT_CONFIG_LOCAL" << 'EOF'
[credential]
    helper = osxkeychain
EOF
            ;;
    esac
fi


# Starship config
link_file "$DOTFILES_DIR/.config/starship.toml" "$HOME/.config/starship.toml"

# Emacs
mkdir -p ~/.emacs.d
link_file "$DOTFILES_DIR/.emacs.d/init.el" "$HOME/.emacs.d/init.el"
link_file "$DOTFILES_DIR/.emacs.d/inits" "$HOME/.emacs.d/inits"
#link_file "$DOTFILES_DIR/.emacs.d/package-install.el" "$HOME/.emacs.d/package-install.el"
#link_file "$DOTFILES_DIR/.emacs.d/packages" "$HOME/.emacs.d/packages"
mkdir -p ~/tmp
mkdir -p ~/.emacs_backup


if [ -e ~/.ssh/ssh-add-all ]; then
    chmod +x ~/.ssh/ssh-add-all
fi
