#!/bin/bash
# session-sync-init.sh - Initialize ~/.claude/projects as a git repo for session sync
# Usage: Called by install.sh, or manually: ./session-sync-init.sh
# Syncs session JSONL in projects/ to private repo nirecom/claude-sessions

set -euo pipefail

CLAUDE_DIR="$HOME/.claude"
REMOTE_URL="git@github.com:nirecom/claude-sessions.git"
NO_REMOTE=false

while [ $# -gt 0 ]; do
    case "$1" in
        --claude-dir) CLAUDE_DIR="$2"; shift 2 ;;
        --remote-url) REMOTE_URL="$2"; shift 2 ;;
        --no-remote) NO_REMOTE=true; shift ;;
        *) shift ;;
    esac
done

if ! type git >/dev/null 2>&1; then
    echo "Git is required for session sync." >&2
    exit 1
fi

PROJECTS_DIR="$CLAUDE_DIR/projects"
mkdir -p "$PROJECTS_DIR"

# Migrate old git root from ~/.claude/ to ~/.claude/projects/
if [ -d "$CLAUDE_DIR/.git" ]; then
    echo "Migrating git root from $CLAUDE_DIR to $PROJECTS_DIR..."
    rm -rf "$CLAUDE_DIR/.git"
    rm -f "$CLAUDE_DIR/.gitignore" "$CLAUDE_DIR/.gitattributes"
fi

# Initialize git repo if not already
if [ ! -d "$PROJECTS_DIR/.git" ]; then
    echo "Initializing git repo in $PROJECTS_DIR..."
    git init "$PROJECTS_DIR"
    # Disable commit hooks (private repo; JSONL contains paths that trigger private-info hooks)
    git -C "$PROJECTS_DIR" config core.hooksPath /dev/null
else
    echo "Git repo already exists in $PROJECTS_DIR."
fi

# Create .gitattributes (overwrite for idempotency)
printf '# All files under this repo are machine-generated by Claude Code\n* text eol=lf\n' > "$PROJECTS_DIR/.gitattributes"

# Set remote
if ! "$NO_REMOTE"; then
    existing=$(git -C "$PROJECTS_DIR" remote 2>/dev/null || true)
    if echo "$existing" | grep -qx "origin"; then
        git -C "$PROJECTS_DIR" remote set-url origin "$REMOTE_URL"
    else
        git -C "$PROJECTS_DIR" remote add origin "$REMOTE_URL"
    fi
    echo "Remote set to $REMOTE_URL"
fi

# Initial commit if no commits yet
commit_count=$(git -C "$PROJECTS_DIR" rev-list --count HEAD 2>/dev/null || echo 0)
if [ "$commit_count" -eq 0 ]; then
    # Pull existing remote history first (e.g., synced from another machine)
    if ! "$NO_REMOTE"; then
        git -C "$PROJECTS_DIR" fetch origin main 2>/dev/null && \
            git -C "$PROJECTS_DIR" reset origin/main 2>/dev/null || true
    fi
    git -C "$PROJECTS_DIR" add .gitattributes
    git -C "$PROJECTS_DIR" add .
    git -C "$PROJECTS_DIR" commit -m "Initial session sync from $(hostname -s)" 2>/dev/null || true
    if ! "$NO_REMOTE"; then
        git -C "$PROJECTS_DIR" push -u origin main 2>/dev/null || git -C "$PROJECTS_DIR" push -u origin master 2>/dev/null || true
    fi
fi

echo "Session sync initialized."
